### ISSUE TITLE
Check eligibility

### ISSUE THREAD

**Issue by danielmlow** [sensein/covid19#1]
@sanuann @satra 

Perhaps the study should check answers to determine eligibility, right? As is, it just accepts anything. So perhaps:

1. make sure email has "@" and ".com"?

2. Make sure year of birth is older than 2004?

![image](https://user-images.githubusercontent.com/14787791/80228398-61be6100-8625-11ea-9f9f-909e09da9050.png)

**Comment by satra** [comment]
@sanuann - for the string entry component is there a way to run regexp based validation. if not, perhaps email should be a specific component. 

@daniel - `.com` is not a good validator for email. 

here is a potential email validator: https://www.w3resource.com/javascript/form/email-validation.php

**Comment by sanuann** [comment]
since there weren't existing widgets for email and some other types, i mapped them to text for the time being. 
regex based validation should work i think. I will look into it.

**Comment by satra** [comment]
@danielmlow - i'm going to close this issue, but the questions and the flow of this protocol should now be adjusted to reflect the approved IRB changes.
