### ISSUE TITLE
add spanish to buttons

### ISSUE THREAD

**Issue by danielmlow** [sensein/covid19#17]
@sanuann we need to change the buttons to be available in Spanish: 1. landing page “Join”, 2. “Submit” for checkboxes, 3. “Start”, “Play”, “Redo recording” “Continue” for audioCheck, 4. “record” and “stop” for all other voice tasks, 5. “Next” for switching between activities, 6. “Thank You for participating!  Please save your data now. ” and “Upload” at the end

Where I can find these?

I can add them, if not here are the Spanish translations:
Join > Participar
Submit > Enviar
Start > Comenzar
Play > Play
Redo recording > Vuelva a grabar
Continue > Continuar
Record > Grabar
Stop > Parar
Next > Siguiente
Thank You for participating!  Please save your data now > ¡Gracias por participar! Por favor guarde sus datos ahora. 
Upload > Enviar

**Comment by sanuann** [comment]
this has been completed now. closing it
