### ISSUE TITLE
Set up more elegantly: different questions depending on answer

### ISSUE THREAD

**Issue by danielmlow** [sensein/covid19#3]
Once the pull request is accepted, you can see the new protocol with covid19 questionnaire here:
```
https://schema.repronim.org/ui/#/?url=https://raw.githubusercontent.com/sensein/covid19/master/protocol/Covid19_schema
```

This protocol runs well, but could be set up more elegantly. maybe @sanuann can help me set this up if @satra agrees we need the changes (maybe we confirm we'll deploy before putting in the extra work):

1. The first item (at the bottom) is covid19/items/covid19_status. Here depending on if the person says they were tested or not, different options would appear (3 if they were not test and 2 if they were tested).

2. covid19/items/covid19_diagnosis. This question is redundant but I think it may be necessary to not miss a confirmed case and is very quick to answer. 

@satra 
3. covid19/items/covid19_days: If they answer "Yes" to question 2, then this third question would appear. This question isn't totally necessary because we're asking about symptoms BEFORE diagnosis. 

![image](https://user-images.githubusercontent.com/14787791/80379880-139f9c80-8875-11ea-90b8-edbec37bd1ed.png)

4. covid19/items/covid19_symptoms: This question should change depending one what they answer in 2 or 3. if they were NOT diagnosed then it can ask: "Are you currently experiencing any of the following symptoms?" If they WERE diagnosed then "Check the symptoms you had before being tested for COVID-19."
![image](https://user-images.githubusercontent.com/14787791/80380706-501fc800-8876-11ea-89a8-012e1eb1317b.png)

5. covid19/items/fever: beyond providing answer in text form, we should allow people to choose Celcius or Farenheit, but it won't show both inputType: text and responseOptions with inputType: radio
![image](https://user-images.githubusercontent.com/14787791/80382605-d9d09500-8878-11ea-89fd-36d9eb064191.png)

```
    "responseOptions": {
        "multipleChoice": true,
        "choices": [{
                "value": 1,
                "name": {
                    "en": "Fahrenheit",
                    "es": "Fahrenheit"
                }},
            {
                "value": 2,
                "name": {
                    "en": "Celcius",
                    "es": "Celcius"
                }}
]}
```

**Comment by satra** [comment]
@danielmlow - this can already be done through the visibility option.  see this section here: https://github.com/ReproNim/reproschema/blob/master/activities/Wellbeing/Wellbeing_schema#L32

**Comment by danielmlow** [comment]
@satra Ok, so I'd need to create new items `covid19_status_tested` and  `covid19_status_notTested` for the suboptions which would be accessed like this?

```
        "visibility": [
            {"variableName": "covid19_status_tested", "isVis": "covid19_status" === 1"},
            {"variableName": "covid19_symptoms_tested", "isVis": "covid19_status" === 0"}
``` 

I need to finish something for another project but I'll get back to this tomorrow so I can test it properly.

**Comment by danielmlow** [comment]
@sanuann 
1. The ways I set it up, it's not working
https://github.com/danielmlow/covid19/blob/master/covid19/covid19_schema

I copied the example Satra sent me above:
https://github.com/ReproNim/reproschema/blob/master/activities/Wellbeing/Wellbeing_schema#L32

If I select option 1 in /covid19_status, it does not branch to the right question /covid19_status_notTested (and the same for the other branches):
<img width="968" alt="visibility" src="https://user-images.githubusercontent.com/14787791/80628099-3c679380-8a27-11ea-8ba7-8f41e686811f.png">
