### ISSUE TITLE
"Help" button for feedback

### ISSUE THREAD

**Issue by danielmlow** [sensein/covid19#30]
Add a "Help" button which can either appear at all times in a corner or in the menu. If you click on it it is a mail_to which sends an email to voice_survey@mit.edu and people can specify the issue they found.

If possible: prepopulate email with users browser and device specs (Macbook Pro version, Chrome version), as much detail as possible.

**Comment by sanuann** [comment]
@danielmlow this one is done. pls review it here: https://www.repronim.org/reproschema-ui/#/ and if it looks good, then let me know. I will update the UI checksum in this repo.

**Comment by danielmlow** [comment]
Looks great, thanks!

**Comment by danielmlow** [comment]
@satra 

I would keep this function but my guess is that most macbook users have not set up an account (e.g. gmail) and so this Help button will not end up sending the info. However, as you said most iphone user do, and many will do it from their iphone or android devices. I have my send_to configured to send from Gmail, but this is what I get when I try to send an email from the Mail app. Since this would take people several minutes to figure out how to set up an account, most would abandon the attempt. This is just so we know:

![image](https://user-images.githubusercontent.com/14787791/102988762-314fff00-44f3-11eb-9a1b-b606f97cccda.png)
![image](https://user-images.githubusercontent.com/14787791/102988781-39a83a00-44f3-11eb-9857-3dc2a06e09ab.png)

**Comment by sanuann** [comment]
sending email from the mail app works for me, however, I forgot how I had set it up..

**Comment by danielmlow** [comment]
@sanuann merge this feature. We'll give people the form option as well in the email we send them. Or you can include it somehow: https://docs.google.com/forms/d/e/1FAIpQLScekjo0BTkg0NFG67SO3Rzpps9ltrRY-ffVPbR99dlmIXgEkg/viewform?usp=sf_link 

Also, remove "This protocol is under construction" banner.

**Comment by sanuann** [comment]
I'll remove the banner. Trying to put in the timer if expiry_time available.
