### ISSUE TITLE
First round of feedback

### ISSUE THREAD

**Issue by danielmlow** [sensein/covid19#31]
**Urgent:**

- [x] As you know the blue radio buttons don't work well on safari (tested on two different iphone 8): "On my iPhone, I had trouble hitting the tiny circles for the questionnaires, and often had to scroll back down to fix a dot I missed, so I was glad to have the review option. (NPS)"

**Less urgent:**

- [x] When people press submit, there is an instruction: 
"Thank you for participating!
Please save your data now."
When people click Upload, we want this message to appear:
en: (instruction) “(Uploading... This generally takes a few seconds for fast connections or longer depending on your connection speed).” 
es: (instruction) "(Enviando... Esto generalmente demora un par de segundos para conexiones veloces o más dependiendo de su velocidad de conexión)". 
If you can, add "Uploading/Enviando X MB... " e.g., "Uploading 56 MB" which you would extract somehow. It's possible, but if it's hard leave it for later. 

- [x] Disable exporting data for this project. 

- [x] covid19_clinical_history:  Add "No, none of these" as an option at the bottom

In reproschema-library:
- [x] cough: edit to this:
"en": "Inhale, cough 3 times. Repeat two more times.",
"es": "Debe inhalar y luego toser 3 veces. Repite esto dos veces más. "
- [x] in all kmart tasks (kmart_exhale, kmart_inhale, kmart_natural)
    * en: Change "coke" to "Coke"
    * es: Change "coca cola" to "Coca Cola"

- [x] In covid19/activity/voice_opt/voice_opt_schema:
change order to:
            "voice_tasks:say_ee",
            "voice_tasks:deep_breath",
            "voice_tasks:free_speech_general_mood",
            "voice_tasks:say_m",
            "voice_tasks:kmart_natural",
            "voice_tasks:kmart_inhale",
            "voice_tasks:say_oo",
            "voice_tasks:nasal_high",
            "voice_tasks:say_n",
            "voice_tasks:free_speech_food",

- [x] move this item from voice_opt_schema to voice tasks
            "voice_tasks:free_speech_general_mood",

- [x] change the testing question to have an `"I'm waiting for test results."` option. and skip asking about the test if that option is selected and instead simply ask for test date.

- [x] update the symptom list to reflect latest symptoms for covid. perhaps ask about current symptoms as the first question. (leave for when we do the amendment)

- [x] Provide an option to skip the current temperature question. Many people may not know their current temperature.

**Comment by danielmlow** [comment]
could you also change the mental health items to regular items here: https://github.com/sensein/covid19/blob/master/activity/MentalHealth/MentalHealth_schema#L32 


instead of sub-activities change them to “phq9_1”, “phq9_2",  “gad7_1”, etc.

and then delete phq2 activity from that repo

**Comment by danielmlow** [comment]
@sanuann 
> * [x]  change the testing question to have an `"I'm waiting for test results."` option. and skip asking about the test if that option is selected and instead simply ask for test date.

schema: https://github.com/sensein/covid19/blob/master/activity/covid19/covid19_schema

I finished this but it's not working. I added a new option 3 to "I'm waiting for test results.":
https://github.com/sensein/covid19/blob/master/activity/covid19/items/covid19_status_tested

If they select 3, then they are asked about the date (I obtained this template from some other activity in the library):
https://github.com/sensein/covid19/blob/master/activity/covid19/items/covid19_date_test

I change to schema version to rc2. I'm guessing there's something off in covid19_date_test.

**Comment by sanuann** [comment]
> https://github.com/sensein/covid19/blob/master/activity/covid19/covid19_schema

you haven't added the new item (`covid19_date_test`) to the`order` array!

**Comment by danielmlow** [comment]
> > https://github.com/sensein/covid19/blob/master/activity/covid19/covid19_schema
> 
> you haven't added the new item (`covid19_date_test`) to the`order` array!

Ah, sorry about that. please add `"items/covid19_date_test",` in between these two:
![image](https://user-images.githubusercontent.com/14787791/102556700-81643700-4097-11eb-92cb-e17ec63d480d.png)


Here: https://github.com/sensein/covid19/blob/3b998111345fdc41ccf78ec865ee284302858a7d/activity/covid19/covid19_schema#L26

**Comment by satra** [comment]
@sanuann - when i go to the current website, i don't get the export option, but i get the submit option. 

the submit option should only appear if the url has the right parameters, while the export option should appear if the submit capability is not there.

**Comment by satra** [comment]
there is one remaining issue in the list above that needs to be fixed.

**Comment by danielmlow** [comment]
Rainbow passage: fix comma: "There is , according"

**Comment by danielmlow** [comment]
The output are files like this:
`20201222T152938.019017Z0000-1d911c4d-dd82-44ff-bf31-1c94f034be6e-6.zip`
When you unzip we get a file called `responses`, but it would be better to get the same name as the zip file for the unzipped file instead.

**Comment by satra** [comment]
can we do this: `responses/<projectname>/sub-<uid>/<data>` ?

**Comment by danielmlow** [comment]
This continues here: https://github.com/sensein/covid19/issues/52
