### ISSUE TITLE
make say vowels longer

### ISSUE THREAD

**Issue by danielmlow** [sensein/covid19#36]
@satra, a participant was able to say_ah for longer than the max (30 sec). I don't want a ceiling effect but also want to reduce the risk of people thinking they should take a second breath and continue if it's 45 or 60sec (saw this, although rarely, in the VFP dataset). I suggest 45sec. What do you suggest?

@sanuann, could you make all the say_ah and other ones here longer once Satra confirms: https://github.com/ReproNim/reproschema-library/tree/master/activities/VoiceTask/items
For this study (covid19) but also as the standard.

**Comment by danielmlow** [comment]
Actually, I think singers/opera singers will definitely be able to go on for a while. And they're easy to recruit as participants given our voice therapist colleagues. So 60sec?

**Comment by satra** [comment]
we can do 60s. also please remove the optional voice tasks.

**Comment by sanuann** [comment]
I don't know why I do not get any notifications these days from any of the mentions or comments (though it says I am subscribed to this thread). So please ping me on slack if something is urgent. Thanks.

**Comment by sanuann** [comment]
this one is done in reproschema-library voice items. closing it
