### ISSUE TITLE
mic issues (adding instructions)

### ISSUE THREAD

**Issue by danielmlow** [sensein/covid19#43]
Hi, 

A participant says "Microphone did now work, could not record" using Chrome and iphone 12. 

They gave us that info using the form I created. We know who the participant is so we can have them test it again if needed.

**Comment by sanuann** [comment]
perhaps the person had previously denied access to the microphone? can you check with him/her @danielmlow ?

**Comment by danielmlow** [comment]
What instructions should I give them if that were the case? Could there be
any other issue?

**Comment by danielmlow** [comment]
I think the most common issue might be having blocked the function it in the past. So it's easy to re-activate. I suggest we add instructions at the audio-check item. We can either provide links to websites explaining how to unblock or synthesize steps to make it easier. @satra which do you think is best? 

For instance, here is a step for computers using chrome: 
![image](https://user-images.githubusercontent.com/14787791/103369402-ca10ec80-4aa8-11eb-8ca7-1263ca3c7d1f.png)

We could try to synthesize that depending on the device and browser or add links like this:
en: "You may need to unblock your mic access following these instructions:"  https://support.google.com/chrome/answer/2693767?co=GENIE.Platform%3DDesktop&hl=en
es: "Debe desbloquear el acceso a su micrófono siguiendo estas instrucciones:"  https://support.google.com/chrome/answer/2693767?co=GENIE.Platform%3DDesktop&hl=es

(Note the "en" vs. "es" at the end of the urls).

**Comment by satra** [comment]
see this: https://stackoverflow.com/a/51078209/1179425

i think a check like that needs to be in place before any audio recording, and then instruct the user to re-enable it. the instructions for re-enabling should be very simple.  the instructions above are too complicated for most folks. on computers, this can be done through the url bar. on phones/tablets one would need to check across browsers.

**Comment by danielmlow** [comment]
@sanuann, can you implement that check? I can write simple instructions to re-enable it, but can we choose the instruction I'll write within audio_check (i.e., a different version of the audio_check) by automatically seeing what browser and device they're on? Or should we write instruction for all devices/browsers in the same item?

**Comment by sanuann** [comment]
a check like that already exists: https://github.com/ReproNim/reproschema-ui/blob/master/src/components/Inputs/AudioCheck/AudioCheck.vue#L234

We need to add instruction to re-enable it if it's blocked in the past.

**Comment by danielmlow** [comment]
@satra should we (A) add all instructions for all browsers in the same item or (B) first detect device+browser and based on that show certain instructions?

**Comment by satra** [comment]
> (B) first detect device+browser and based on that show certain instructions?

**Comment by sanuann** [comment]
perhaps we can do something like this done here: https://www.voiceome.org/covid19/index.html
(see video)


https://user-images.githubusercontent.com/5114945/103377364-37268100-4aad-11eb-99ac-23b266d6240d.mov

**Comment by danielmlow** [comment]
Hi @sanuann,
We need to detect what browser and device the participant is on. Based on that, we’ll give these instructions to activate the mic right on the same item as the audio_check I suppose (i.e., we'll expand audio check to include these instructions or create a popup with the instructions and a participant will only see the one relevant to their device and browser). Could you try filling in the rest of the instructions. Once we're done, I'll translate to Spanish.

Here is a link to test:
https://sensein.github.io/covid19/#/?auth_token=covid19-85181ac586844081afa8cb0c8aae0cce&expiry_time=2021-01-22T16%3A52%3A04.846449%2000%3A00&uid=1

Instructions to Activate mic (remove "Chrome" and Device this is just for our use):
Chrome:
- Computer: Instructions to activate microphone\n At the top right, click the three vertical dots, then "Settings". Under "Privacy and security," click "Site settings". Click "Microphone". Turn on "Ask before accessing (recommended)". Please re-click on the link we sent you to your email, your previous answers were saved.  
- Android: Instructions to activate microphone\n At the top right, click the three vertical dots, then "Settings". Under "Privacy and security," click "Site settings". Click "Microphone". Turn on "Ask before accessing (recommended)". Please re-click on the link we sent you to your email, your previous answers were saved. 
- iphone/ipad: Instructions to activate microphone\n Please use Safari browser. Go back to the email, press and hold on your unique link, copy link and past in Safari browser. 

Safari:
- Computer: Click on the Safari tab > Preferences, then click Websites. Then choose "Ask" in the bottom right. Please re-click on the link we sent you to your email, your previous answers were saved.  
- Android: 
- iphone/ipad: Instructions to activate microphone\n Launch Settings from your Home screen. Tap Safari (scroll down). Go to "Microphone" (towards the bottom). Choose "Ask". Please re-click on the link we sent you to your email, your previous answers were saved.  

Mozilla:
- Computer
- Android
- iphone/ipad

**Comment by danielmlow** [comment]
@satra Note above I say that if you're using Chrome on an iPhone, switch to Safari. The reason is because I received the following error (on Iphone 8):

![image](https://user-images.githubusercontent.com/14787791/104769188-ea91a580-573c-11eb-80b8-bbdadb389469.png)

Maybe we could instruct people to use certain browsers depending on device?
