### ISSUE TITLE
Fix temperature instructions

### ISSUE THREAD

**Issue by danielmlow** [sensein/covid19#46]
Since it is optional, 

please remove "Please enter number" and exclamation point since it is optional (if not people will think they need to enter a number). 
![image](https://user-images.githubusercontent.com/14787791/104763474-ef059080-5733-11eb-9a7b-41dae378aca3.png)

**Comment by danielmlow** [comment]
Also this: https://github.com/sensein/covid19/commit/39d4bc6c8f3ac44676cd983e8c93a4c779d94f2e

**Comment by sanuann** [comment]
this one is done
