### ISSUE TITLE
Menu button does not work on iphone

### ISSUE THREAD

**Issue by danielmlow** [sensein/covid19#47]
@sanuann 
Clicking on the the 3 horizontal lines does nothing. Sometimes it highlights the "Help" button (which works), sometimes it zooms in. But even then, clicking on the the 3 lines does nothing. 

iPhone 8
Browser: Chrome and Safari

This is needed to skip or to change languages

highlighting the Home button:
![image](https://user-images.githubusercontent.com/14787791/104768839-4c9ddb00-573c-11eb-9d7a-7851691c52a9.png)

Zooming in:
![image](https://user-images.githubusercontent.com/14787791/104768899-62130500-573c-11eb-92ae-e3979fdd6e82.png)

**Comment by sanuann** [comment]
hopefully, this should be fixed now. please check and close @danielmlow
