### ISSUE TITLE
edit expiry banner

### ISSUE THREAD

**Issue by danielmlow** [sensein/covid19#51]
![image](https://user-images.githubusercontent.com/14787791/107074502-d3cbf500-67b6-11eb-9f63-09178dae2b50.png)
"Please contact the researchers for a new link with an email to voice_survey@mit.edu"

es: "Por favor contacte a los investigadores para un nuevo enlace escribiendo un email a voice_survey@mit.edu"

**Comment by danielmlow** [comment]
@sanuann this still needs to be done.

**Comment by sanuann** [comment]
done.
