### ISSUE TITLE
Edits

### ISSUE THREAD

**Issue by danielmlow** [sensein/covid19#60]
1) Please double check edits and merge PRs here:
https://github.com/ReproNim/reproschema-library/pulls

2) Edit (it doesnt let me edit)
2.1) "tareasde" to "tareas de" 
2.2.) "Detener" to "Parar" 
here:
https://github.com/sensein/covid19/blob/66df005b11945505d3cdf27da0138d4c781c9b3e/activity/voice/voice_schema#L16

**Comment by sanuann** [comment]
done.
